mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/meteorite/', permanent=True)),
    path('meteorite/', include('meteorite.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
]

handler404 = 'mysite.views.custom_404_view'
handler500 = 'mysite.views.custom_500_view'

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:meteorite_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('buy-now/<int:meteorite_id>/', views.buy_now, name='buy_now'),
    path('detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    USER_TYPE_CHOICES = [
        ('admin', 'Admin'),
        ('normal', 'Normal'),
    ]
    usertype = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    reg_time = models.DateTimeField(auto_now_add=True)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('meteorite:homepage')
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('meteorite:homepage')  # Jump to login after successful registration
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()
    return render(request, 'user/register.html', {'form': form})

def user_login(request):
    if request.user.is_authenticated:
        return redirect('meteorite:homepage')
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('meteorite:homepage')  # Jump to homepage after successful login
    else:
        form = UserLoginForm()
    return render(request, 'user/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('meteorite:homepage')  # Jump to homepage after logging out

@login_required
def profile(request):
    return render(request, 'user/profile.html')

templates/user/login.html
{% extends 'meteorite/main.html' %}

{% block title %}User Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <h3>No accounts? <a href="{% url 'user:register' %}">Register Here!</a></h3>
{% endblock %}

templates/user/profile.html
{% extends 'meteorite/main.html' %}

{% block title %}Your Profile{% endblock %}

{% block content %}
    <div style="padding:5px;">
        <h2>Welcome, {{ user.username }}!</h2>
        <p>Email: {{ user.email }}</p>
        <p>User Type: {{ user.usertype }}</p>
        <p>Registered at: {{ user.reg_time }}</p>

        <a href="{% url 'user:logout' %}"><button>Logout</button></a>
    </div>
    <div style="padding:20px;">
        <a href="{% url 'order:my_orders' %}">See All Orders</a>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'meteorite/main.html' %}

{% block title %}User Registration{% endblock %}

{% block content %}
    <h2>Register</h2>
    {% if form.errors %}
        <ul class="errorlist">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}